import test from 'node:test';
import assert from 'node:assert/strict';
import {consumeAiQuota,anonymousAiEnabled,AiHttpError} from '../lib/ai-rate-limit.ts';
const req=ip=>new Request('https://kalora.test/api/analyze',{headers:{'x-forwarded-for':ip}});
const result=(status,data)=>new Response(JSON.stringify(data),{status});
test('persistent server quota',async t=>{
 process.env.NEXT_PUBLIC_SUPABASE_URL='https://database.test';process.env.SUPABASE_SERVICE_ROLE_KEY='server-secret';process.env.VERCEL='1';
 await t.test('anonymous access requires explicit opt-in',async()=>{delete process.env.ALLOW_ANONYMOUS_AI;assert.equal(anonymousAiEnabled(),false);let calls=0;globalThis.fetch=async()=>{calls++;return result(200,{allowed:true,retry_after:0})};await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e.status===401);assert.equal(calls,0);process.env.ALLOW_ANONYMOUS_AI='true'});
 await t.test('anonymous IP is hashed; defaults and server-only RPC are used',async()=>{globalThis.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);assert.match(url,/consume_ai_request_quota$/);assert.equal(opts.headers.apikey,'server-secret');assert.match(body.subject,/^anon:[a-f0-9]{64}$/);assert.ok(!opts.body.includes('1.2.3.4'));assert.equal(body.hour_limit,10);assert.equal(body.day_limit,20);return result(200,{allowed:true,retry_after:0})};await consumeAiQuota(req('1.2.3.4'))});
 await t.test('IPv6 rotation inside /64 shares a bucket',async()=>{const subjects=[];globalThis.fetch=async(_,opts)=>{subjects.push(JSON.parse(opts.body).subject);return result(200,{allowed:true,retry_after:0})};await consumeAiQuota(req('2001:db8::1'));await consumeAiQuota(req('2001:0db8:0:0::abcd'));assert.equal(subjects[0],subjects[1])});
 await t.test('untrusted forwarding headers share fallback outside Vercel',async()=>{delete process.env.VERCEL;const subjects=[];globalThis.fetch=async(_,opts)=>{subjects.push(JSON.parse(opts.body).subject);return result(200,{allowed:true,retry_after:0})};await consumeAiQuota(req('1.2.3.4'));await consumeAiQuota(req('9.8.7.6'));assert.equal(subjects[0],subjects[1]);process.env.VERCEL='1'});
 await t.test('authenticated quota retains 40/hour',async()=>{globalThis.fetch=async(_,opts)=>{const body=JSON.parse(opts.body);assert.equal(body.hour_limit,40);assert.equal(body.subject,'user:00000000-0000-4000-8000-000000000001');return result(200,{allowed:true,retry_after:0})};await consumeAiQuota(req('1.2.3.4'),'00000000-0000-4000-8000-000000000001')});
 await t.test('429 contains a retry delay and understandable message',async()=>{globalThis.fetch=async()=>result(200,{allowed:false,retry_after:120,scope:'subject'});await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e instanceof AiHttpError&&e.status===429&&e.retryAfter===120&&e.message.includes('2 min'));globalThis.fetch=async()=>result(200,{allowed:false,retry_after:3600,scope:'global'});await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e.status===429&&e.message.includes('ukupni'))});
 await t.test('missing secret, database failure, malformed result and network failure fail closed',async()=>{for(const response of [async()=>result(500,{error:'secret details'}),async()=>result(200,{allowed:true}),async()=>{throw new Error('secret details')}]){globalThis.fetch=response;await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e.status===503&&!e.message.includes('secret details'))}delete process.env.SUPABASE_SERVICE_ROLE_KEY;await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e.status===503);process.env.SUPABASE_SERVICE_ROLE_KEY='server-secret'});
 await t.test('invalid configuration cannot disable quota',async()=>{process.env.AI_GLOBAL_PER_DAY='0';await assert.rejects(consumeAiQuota(req('1.2.3.4')),e=>e.status===503);delete process.env.AI_GLOBAL_PER_DAY});
});

test('authorization and HTTP errors',async t=>{
 const {readFile}=await import('node:fs/promises');
 const {stripTypeScriptTypes}=await import('node:module');
 let source=await readFile(new URL('../lib/ai-server.ts',import.meta.url),'utf8');
 source=source.replaceAll("'zod'",JSON.stringify(import.meta.resolve('zod'))).replaceAll("'./domain'",JSON.stringify(new URL('../lib/domain.ts',import.meta.url).href)).replaceAll("'./ai-rate-limit'",JSON.stringify(new URL('../lib/ai-rate-limit.ts',import.meta.url).href));
 const {authorize,errorResponse}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
 process.env.OPENAI_API_KEY='private-openai';process.env.NEXT_PUBLIC_SUPABASE_URL='https://database.test';process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='public-anon';process.env.SUPABASE_SERVICE_ROLE_KEY='server-secret';process.env.ALLOW_ANONYMOUS_AI='true';
 await t.test('expired login cannot fall back to anonymous quota',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;return result(401,{})};await assert.rejects(authorize(new Request('https://kalora.test',{headers:{authorization:'Bearer expired'}})),e=>e.status===401);assert.equal(calls,1)});
 await t.test('server quota uses verified user id and produces a real 429 response',async()=>{let calls=0;globalThis.fetch=async(url,opts)=>{calls++;if(url.endsWith('/user'))return result(200,{id:'00000000-0000-4000-8000-000000000001'});assert.equal(JSON.parse(opts.body).user_id,'00000000-0000-4000-8000-000000000001');return result(200,{allowed:false,retry_after:120,scope:'subject'})};let caught;try{await authorize(new Request('https://kalora.test',{headers:{authorization:'Bearer valid'}}))}catch(e){caught=e}const response=errorResponse(caught);assert.equal(response.status,429);assert.equal(response.headers.get('Retry-After'),'120');assert.equal(response.headers.get('Cache-Control'),'no-store');const body=await response.text();assert.match(body,/limit/);assert.ok(!body.includes('server-secret'));assert.ok(!body.includes('private-openai'));assert.equal(calls,2)});
});
