import test from 'node:test';
import assert from 'node:assert/strict';
import {stateSchema,initialState,makeWaterEntry,withWaterEntries,waterForDate,waterTotal,undoWaterChange,loggedTime,itemSchema,makeItem,baseFoods} from '../lib/domain.ts';
const date='2026-10-01';
test('legacy water totals migrate once without invented timestamps',()=>{const old=initialState(false);delete old.waterEntries;old.water={[date]:1080,'2026-09-30':750,'2026-09-29':0};const migrated=stateSchema.parse(old);assert.equal(migrated.waterEntries.length,2);assert.equal(migrated.waterEntries[0].loggedAt,null);assert.equal(migrated.waterEntries[0].id,'legacy-water-'+date);assert.deepEqual(stateSchema.parse(JSON.parse(JSON.stringify(migrated))),migrated);assert.equal(waterTotal(migrated.waterEntries,date),1080)});
test('every water click has its own id and real timestamp, independent of diary date',()=>{const now=new Date('2026-10-01T11:44:31.123Z');const a=makeWaterEntry(250,'2026-09-30',now),b=makeWaterEntry(250,'2026-09-30',now);assert.notEqual(a.id,b.id);assert.equal(a.loggedAt,now.toISOString());assert.equal(a.date,'2026-09-30');assert.equal(loggedTime(a.loggedAt),'13:44')});
test('delete 330 ml from 1080 leaves 750 and preserves other dates',()=>{let s=initialState(false);const entries=[250,330,500].map(ml=>makeWaterEntry(ml,date));const other=makeWaterEntry(100,'2026-09-30');s=withWaterEntries(s,[...entries,other]);assert.equal(s.water[date],1080);s=withWaterEntries(s,s.waterEntries.filter(e=>e.id!==entries[1].id));assert.equal(waterTotal(s.waterEntries,date),750);assert.equal(s.water[date],750);assert.equal(s.water['2026-09-30'],100);assert.equal(waterForDate(s.waterEntries,date).length,2)});
test('deleting all entries cannot resurrect legacy or stale summary values',()=>{const old=initialState(false);delete old.waterEntries;old.water[date]=1080;const migrated=stateSchema.parse(old);const empty=withWaterEntries(migrated,[]);assert.equal(empty.water[date],0);const restored=stateSchema.parse({...empty,water:{[date]:1080}});assert.equal(restored.water[date],0);assert.deepEqual(restored.waterEntries,[])});
test('timestamps and ids survive offline export/import exactly',()=>{const s=withWaterEntries(initialState(false),[makeWaterEntry(330,date,new Date('2026-10-01T08:15:00.000Z'))]);s.items=[makeItem(baseFoods[0],120,'breakfast',date)];s.items[0].loggedAt='2026-10-01T06:31:00.000Z';const roundTrip=stateSchema.parse(JSON.parse(JSON.stringify(s)));assert.deepEqual(roundTrip.waterEntries,s.waterEntries);assert.equal(roundTrip.items[0].loggedAt,'2026-10-01T06:31:00.000Z');assert.equal(loggedTime(roundTrip.items[0].loggedAt),'08:31')});
test('legacy food has unknown time and edits preserve original save time',()=>{const item=makeItem(baseFoods[0],120,'breakfast',date);const old={...item};delete old.loggedAt;assert.equal(itemSchema.parse(old).loggedAt,null);assert.equal(itemSchema.parse({...item,grams:150}).loggedAt,item.loggedAt)});
test('invalid entries, duplicate ids and over-limit daily sums fail validation',()=>{const entry=makeWaterEntry(250,date);for(const changed of [{...entry,amountMl:0},{...entry,amountMl:-1},{...entry,amountMl:250.5},{...entry,loggedAt:'08:42'},{...entry,loggedAt:null}])assert.equal(stateSchema.safeParse({...initialState(false),waterEntries:[changed]}).success,false);assert.equal(stateSchema.safeParse({...initialState(false),waterEntries:[entry,entry]}).success,false);assert.equal(stateSchema.safeParse({...initialState(false),waterEntries:[{...entry,amountMl:20000},makeWaterEntry(1,date)]}).success,false)});
test('Zagreb time is stable across devices and daylight saving',()=>{assert.equal(loggedTime('2026-01-01T07:42:00Z'),'08:42');assert.equal(loggedTime('2026-07-01T06:42:00Z'),'08:42');assert.equal(loggedTime('2026-07-01T08:42:00+02:00'),'08:42')});

test('undoing one water operation preserves later independent additions',()=>{const a=makeWaterEntry(250,date),b=makeWaterEntry(330,date);assert.deepEqual(undoWaterChange([a,b],[],[a]),[b]);const restored=undoWaterChange([b],[a],[]);assert.equal(waterTotal(restored,date),580);assert.ok(restored.some(e=>e.id===a.id));assert.deepEqual(undoWaterChange([{...a,amountMl:500}],[],[a]),[{...a,amountMl:500}])});
