import test from 'node:test';
import assert from 'node:assert/strict';
import {getSession,saveSession,session,cloudCall,SessionExpiredError,sessionRecoveryMessage} from '../lib/cloud.ts';
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}};
globalThis.localStorage=storage();globalThis.sessionStorage=storage();globalThis.window=new EventTarget();
const old=()=>({access_token:'old',refresh_token:'refresh',expires_at:0,user:{id:'a'}});
const response=(status,data)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('session recovery and refresh concurrency',async t=>{
 await t.test('400 clears only auth, preserves diary and revision, and permits login',async()=>{const diary=JSON.stringify({state:{water:1250,items:['food']},dirty:true,revision:4});localStorage.setItem('kalora-v1-a',diary);saveSession(old());globalThis.fetch=async()=>response(400,{error_code:'refresh_token_not_found'});await assert.rejects(session(),SessionExpiredError);assert.equal(getSession(),null);assert.equal(localStorage.getItem('kalora-v1-a'),diary);assert.match(sessionRecoveryMessage(),/Sesija je istekla/);saveSession({...old(),access_token:'new',expires_at:Date.now()/1000+3600});assert.equal(sessionRecoveryMessage(),'');globalThis.fetch=async()=>response(200,{revision:5});assert.deepEqual(await cloudCall('save_diary',{}),{revision:5})});
 await t.test('network and server errors retain session',async()=>{for(const failure of [async()=>{throw new TypeError('offline')},async()=>response(503,{message:'unavailable'})]){saveSession(old());globalThis.fetch=failure;await assert.rejects(session());assert.equal(getSession().access_token,'old')}});
 await t.test('concurrent refreshes use one request',async()=>{saveSession(old());let count=0;globalThis.fetch=async()=>{count++;return response(200,{...old(),access_token:'fresh',expires_in:3600})};const results=await Promise.all([session(),session(),session()]);assert.equal(count,1);assert.ok(results.every(s=>s.access_token==='fresh'))});
 await t.test('late refresh cannot restore logout or replace a new login',async()=>{for(const next of [null,{...old(),access_token:'other',expires_at:Date.now()/1000+3600}]){saveSession(old());let finish;globalThis.fetch=()=>new Promise(resolve=>finish=resolve);const pending=session();saveSession(next);finish(response(200,{...old(),access_token:'stale',expires_in:3600}));await pending;assert.equal(getSession()?.access_token,next?.access_token)}});
 await t.test('RPC 401 retries refreshed token once and invalid second token expires',async()=>{saveSession({...old(),expires_at:Date.now()/1000+3600});let count=0;globalThis.fetch=async url=>{count++;return url.includes('/auth/')?response(200,{...old(),access_token:'fresh',expires_in:3600}):response(401,{code:'PGRST301'})};await assert.rejects(cloudCall('load_diary',{}),SessionExpiredError);assert.equal(count,3);assert.equal(getSession(),null)});
 await t.test('permission errors do not log out',async()=>{saveSession({...old(),expires_at:Date.now()/1000+3600});globalThis.fetch=async()=>response(403,{message:'permission denied'});await assert.rejects(cloudCall('load_diary',{}),/permission denied/);assert.ok(getSession())});
 await t.test('corrupt auth is removed without clearing unrelated storage',async()=>{localStorage.setItem('kalora-session','broken');localStorage.setItem('kalora-theme','dark');await assert.rejects(session(),SessionExpiredError);assert.equal(localStorage.getItem('kalora-session'),null);assert.equal(localStorage.getItem('kalora-theme'),'dark')});
});
