// Supabase HTTP API: public anon key, with user JWT. Never a service-role key.
export const cloudReady=()=>!!(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
export type Session={access_token:string,refresh_token:string,expires_at:number,user:{id:string,email?:string}};
export function getSession():Session|null{try{return JSON.parse(localStorage.getItem('kalora-session')||'null')}catch{return null}}
export function saveSession(s:Session|null){const oldId=getSession()?.user.id;if(s)localStorage.setItem('kalora-session',JSON.stringify(s));else localStorage.removeItem('kalora-session');if(oldId!==s?.user.id)window.dispatchEvent(new Event('authchange'))}
export async function authRequest(path:string,body:object){const r=await fetch(url+'/auth/v1/'+path,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.message||'Prijava nije uspjela.');if(data.access_token)saveSession({...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in});return data}
let refreshing:Promise<Session|null>|null=null;
export async function session(){let s=getSession();if(s&&s.expires_at<Date.now()/1000+60){if(!refreshing)refreshing=authRequest('token?grant_type=refresh_token',{refresh_token:s.refresh_token}).then(()=>getSession()).finally(()=>{refreshing=null});s=await refreshing}return s}
export async function cloudCall(fn:string,body:object){const s=await session();if(!s)throw new Error('Pričuvajte lokalnu kopiju i ponovno se prijavite.');const r=await fetch(url+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Sinkronizacija nije uspjela.');return d}
export async function consumeMagicLink(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('error_description'))throw new Error(p.get('error_description')!);const token=p.get('access_token');if(token){const r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});if(!r.ok)throw new Error('Poveznica je istekla. Zatraži novu.');const user=await r.json();saveSession({access_token:token,refresh_token:p.get('refresh_token')!,expires_at:Math.floor(Date.now()/1000)+Number(p.get('expires_in')||3600),user});history.replaceState(null,'',location.pathname)}}
export async function signOut(){const s=getSession();try{if(s)await fetch(url+'/auth/v1/logout',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s.access_token}})}finally{saveSession(null)}}
export async function aiCall(path:string,body:object){const s=await session();const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Zahtjev nije uspio.');return d}
