// Supabase HTTP API: public anon key, with user JWT. Never a service-role key.
export const cloudReady=()=>!!(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
export type Session={access_token:string,refresh_token:string,expires_at:number,user:{id:string,email?:string}};
export const SESSION_EXPIRED_MESSAGE='Sesija je istekla. Prijavi se ponovno.';
export class SessionExpiredError extends Error { constructor(){super(SESSION_EXPIRED_MESSAGE);this.name='SessionExpiredError'} }
export function sessionRecoveryMessage(){return sessionStorage.getItem('kalora-auth-recovery')||''}
export function getSession():Session|null{try{const s=JSON.parse(localStorage.getItem('kalora-session')||'null');return s&&typeof s.access_token==='string'&&typeof s.refresh_token==='string'&&Number.isFinite(s.expires_at)&&typeof s.user?.id==='string'?s:null}catch{return null}}
let authGeneration=0;
export function saveSession(s:Session|null){const oldId=getSession()?.user.id;authGeneration++;if(s){localStorage.setItem('kalora-session',JSON.stringify(s));sessionStorage.removeItem('kalora-auth-recovery')}else localStorage.removeItem('kalora-session');if(oldId!==s?.user.id)window.dispatchEvent(new Event('authchange'))}
function expireSession(s:Session){if(getSession()?.access_token!==s.access_token)return;sessionStorage.setItem('kalora-auth-recovery',SESSION_EXPIRED_MESSAGE);saveSession(null)}
export async function authRequest(path:string,body:object){const r=await fetch(url+'/auth/v1/'+path,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.message||'Prijava nije uspjela.');if(data.access_token)saveSession({...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in});return data}
let refreshing: {token:string,promise:Promise<Session|null>}|null=null;
async function refreshSession(s:Session){if(refreshing?.token===s.refresh_token)return refreshing.promise;const gen=authGeneration;const pending={token:s.refresh_token,promise:Promise.resolve(null) as Promise<Session|null>};pending.promise=(async()=>{const r=await fetch(url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});const data=await r.json().catch(()=>({}));if(gen!==authGeneration)return getSession();if(!r.ok){if(r.status===400||r.status===401||r.status===403){expireSession(s);throw new SessionExpiredError()}throw new Error(data.msg||data.error_description||data.message||'Oblak nije dostupan. Pokušaj ponovno.')}if(!data.access_token||!data.refresh_token||!data.user?.id||!Number.isFinite(data.expires_in)){expireSession(s);throw new SessionExpiredError()}saveSession({...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in});return getSession()})().finally(()=>{if(refreshing===pending)refreshing=null});refreshing=pending;return pending.promise}
export async function session(){const s=getSession();if(!s){if(localStorage.getItem('kalora-session')){sessionStorage.setItem('kalora-auth-recovery',SESSION_EXPIRED_MESSAGE);saveSession(null);window.dispatchEvent(new Event('authchange'));throw new SessionExpiredError()}return null}return s.expires_at<Date.now()/1000+60?refreshSession(s):s}
export async function cloudCall(fn:string,body:object){let s=await session();if(!s)throw new SessionExpiredError();for(let attempt=0;attempt<2;attempt++){const r=await fetch(url+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(r.status===401){if(attempt===0){s=await refreshSession(s);if(!s)throw new SessionExpiredError();continue}expireSession(s);throw new SessionExpiredError()}if(!r.ok)throw new Error(d.message||'Sinkronizacija nije uspjela.');return d}}
export async function consumeMagicLink(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('error_description'))throw new Error(p.get('error_description')!);const token=p.get('access_token');if(token){const r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});if(!r.ok)throw new Error('Poveznica je istekla. Zatraži novu.');const user=await r.json();saveSession({access_token:token,refresh_token:p.get('refresh_token')!,expires_at:Math.floor(Date.now()/1000)+Number(p.get('expires_in')||3600),user});history.replaceState(null,'',location.pathname)}}
export async function signOut(){const s=getSession();try{if(s)await fetch(url+'/auth/v1/logout',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s.access_token}})}finally{saveSession(null)}}
export async function deleteAccount(){const s=await session();if(!s)throw new Error('Za brisanje računa moraš biti prijavljen.');const r=await fetch('/api/account/delete',{method:'DELETE',headers:{Authorization:'Bearer '+s.access_token}});const d=await r.json().catch(()=>({}));if(r.status===401){expireSession(s);throw new SessionExpiredError()}if(!r.ok)throw new Error(d.error||'Brisanje računa nije uspjelo.');try{localStorage.removeItem('kalora-v1-'+s.user.id)}finally{saveSession(null)}return d}
export async function aiCall(path:string,body:object){const s=await session();const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body)});const d=await r.json();if(r.status===401&&s){expireSession(s);throw new SessionExpiredError()}if(!r.ok)throw new Error(d.error||'Zahtjev nije uspio.');return d}
